### ISSUE TITLE
Restarting leads to crash due to left over lock file

### ISSUE THREAD

**Issue by ulope** [dappnode/DAppNodePackage-holesky-obol#24]
**Describe the bug**

Restarting the package from the Dappnode UI leads to a crash loop due to a lock file (`voting-keystore.json.lock`) not beking cleaned up properly.

**To Reproduce**

1. Install version `0.1.0 (v0.18.0 upstream)`
2. Configure a validator and join a cluster
3. Restart the validator from the "Info" tab
4. See error in log

Error message:
```
 ✖ Error: EEXIST: file already exists, open '/opt/validator/data/keystores/0x94a8b44af0930af4a4b101f5e0b0ada46543696b7ffaef97e46742a8fb896c49bdccfcaf0aa3b1989ed7d737c1eb0eed/voting-keystore.json.lock'
    at Object.openSync (node:fs:581:18)
    at Module.exports.lockSync (/opt/validator/node_modules/lockfile/lockfile.js:277:17)
    at lockFilepath (file:///opt/validator/packages/cli/src/util/lockfile.ts:26:17)
    at lockKeystore (file:///opt/validator/packages/cli/src/cmds/validator/keymanager/decryptKeystoreDefinitions.ts:112:5)
    at decryptKeystoreDefinitions (file:///opt/validator/packages/cli/src/cmds/validator/keymanager/decryptKeystoreDefinitions.ts:63:5)
    at getSignersFromArgs (file:///opt/validator/packages/cli/src/cmds/validator/signers/index.ts:132:29)
    at Object.validatorHandler [as handler] (file:///opt/validator/packages/cli/src/cmds/validator/handler.ts:91:19)
```

**Expected behavior**

Restart to work

**Screenshots**

**DAppNode version:**

Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.11
core.dnp.dappnode.eth: 0.2.90
dappmanager.dnp.dappnode.eth: 0.2.84, commit: 657ee5f4
https.dnp.dappnode.eth: 0.2.1
ipfs.dnp.dappnode.eth: 0.2.22
wifi.dnp.dappnode.eth: 0.2.9
wireguard.dnp.dappnode.eth: 0.1.3
System info
dockerComposeVersion: 2.21.0
dockerServerVersion: 20.10.24+dfsg1
dockerCliVersion: 20.10.24+dfsg1
os: debian
versionCodename: bookworm
architecture: amd64
kernel: 6.1.0-15-amd64

**Additional context**

A workaround to temporarily get the validator to work again is to log in via SSH and manually delete the lock file:

```
rm /var/lib/docker/volumes/holesky-oboldnpdappnodeeth_validator-1-data/_data/keystores/0x94a8b44af0930af4a4b101f5e0b0ada46543696b7ffaef97e46742a8fb896c49bdccfcaf0aa3b1989ed7d737c1eb0eed/voting-keystore.json.lock
```

Unconfirmed hunch:
Maybe the default docker shutdown grace period for the container is too short for it to properly clean up and remove the lock file.

**Comment by dappnodedev** [comment]
This issue should be solved in the latest versions of the package. Please re-open the issue if you are still experiencing them
